const jdOrderStatus = {
  UNKNOWN: -1,
  INVALID_SPLIT_ORDER: 2,
  INVALID_CANCEL: 3,
  INVALID_JD_BANGBANGZHU_ORDER: 4,
  INVALID_ACCOUNT_EXCEPTION: 5,
  INVALID_GIFT: 6,
  INVALID_SCHOOL_ORDER: 7,
  INVALID_COMPANY_ORDER: 8,
  INVALID_GROUP_BUY_ORDER: 9,
  INVALID_RURAL_ORDER: 11,
  INVALID_VIOLATION_ORDER: 13,
  INVALID_SOURCE_DIFFERENT: 14,
  WAIT_PAYMENT: 15,
  PAYMENT: 16,
  RECEIPT: 17,
  INVALID_REPETITION_ORDER: 20,
  INVALID_CLOUD_STORE_ORDER: 21,
  INVALID_PLUS_FEE_ZERO: 22,
  INVALID_PAYMENT_GIFT: 23,
  PAY_DEPOSIT: 24,
  getName: (value)=> {
    const map = {
      [jdOrderStatus.UNKNOWN]: '未知',
      [jdOrderStatus.INVALID_SPLIT_ORDER]: '无效-拆单',
      [jdOrderStatus.INVALID_CANCEL]: '无效-取消',
      [jdOrderStatus.INVALID_JD_BANGBANGZHU_ORDER]: '无效-京东帮帮主订单',
      [jdOrderStatus.INVALID_ACCOUNT_EXCEPTION]: '无效-账号异常',
      [jdOrderStatus.INVALID_GIFT]: '无效-赠品类目不返佣',
      [jdOrderStatus.INVALID_SCHOOL_ORDER]: '无效-校园订单',
      [jdOrderStatus.INVALID_COMPANY_ORDER]: '无效-企业订单',
      [jdOrderStatus.INVALID_GROUP_BUY_ORDER]: '无效-团购订单',
      [jdOrderStatus.INVALID_RURAL_ORDER]: '无效-乡村推广员下单',
      [jdOrderStatus.INVALID_VIOLATION_ORDER]: '无效-违规订单',
      [jdOrderStatus.INVALID_SOURCE_DIFFERENT]: '无效-来源与备案网址不符',
      [jdOrderStatus.WAIT_PAYMENT]: '待付款',
      [jdOrderStatus.PAYMENT]: '已付款',
      [jdOrderStatus.RECEIPT]: '已完成（购买用户确认收货）',
      [jdOrderStatus.INVALID_REPETITION_ORDER]: '无效-此复购订单对应的首购订单无效',
      [jdOrderStatus.INVALID_CLOUD_STORE_ORDER]: '无效-云店订单',
      [jdOrderStatus.INVALID_PLUS_FEE_ZERO]: '无效-PLUS会员佣金比例为0',
      [jdOrderStatus.INVALID_PAYMENT_GIFT]: '无效-支付有礼',
      [jdOrderStatus.PAY_DEPOSIT]: '已付定金',
    }
    return map[value] || null
  },
  getColor: (value) => {
    const map = {
      [jdOrderStatus.UNKNOWN]: 'info',
      [jdOrderStatus.INVALID_SPLIT_ORDER]: 'danger',
      [jdOrderStatus.INVALID_CANCEL]: 'danger',
      [jdOrderStatus.INVALID_JD_BANGBANGZHU_ORDER]: 'danger',
      [jdOrderStatus.INVALID_ACCOUNT_EXCEPTION]: 'danger',
      [jdOrderStatus.INVALID_GIFT]: 'danger',
      [jdOrderStatus.INVALID_SCHOOL_ORDER]: 'danger',
      [jdOrderStatus.INVALID_COMPANY_ORDER]: 'danger',
      [jdOrderStatus.INVALID_GROUP_BUY_ORDER]: 'danger',
      [jdOrderStatus.INVALID_RURAL_ORDER]: 'danger',
      [jdOrderStatus.INVALID_VIOLATION_ORDER]: 'danger',
      [jdOrderStatus.INVALID_SOURCE_DIFFERENT]: 'danger',
      [jdOrderStatus.WAIT_PAYMENT]: 'primary',
      [jdOrderStatus.PAYMENT]: 'warning',
      [jdOrderStatus.RECEIPT]: 'success',
      [jdOrderStatus.INVALID_REPETITION_ORDER]: 'danger',
      [jdOrderStatus.INVALID_CLOUD_STORE_ORDER]: 'danger',
      [jdOrderStatus.INVALID_PLUS_FEE_ZERO]: 'danger',
      [jdOrderStatus.INVALID_PAYMENT_GIFT]: 'danger',
      [jdOrderStatus.PAY_DEPOSIT]: 'primary',
    }
    return map[value] || 'primary'
  },
  values: ()=> {
    return [
      jdOrderStatus.UNKNOWN,
      jdOrderStatus.INVALID_SPLIT_ORDER,
      jdOrderStatus.INVALID_CANCEL,
      jdOrderStatus.INVALID_JD_BANGBANGZHU_ORDER,
      jdOrderStatus.INVALID_ACCOUNT_EXCEPTION,
      jdOrderStatus.INVALID_GIFT,
      jdOrderStatus.INVALID_SCHOOL_ORDER,
      jdOrderStatus.INVALID_COMPANY_ORDER,
      jdOrderStatus.INVALID_GROUP_BUY_ORDER,
      jdOrderStatus.INVALID_RURAL_ORDER,
      jdOrderStatus.INVALID_VIOLATION_ORDER,
      jdOrderStatus.INVALID_SOURCE_DIFFERENT,
      jdOrderStatus.WAIT_PAYMENT,
      jdOrderStatus.PAYMENT,
      jdOrderStatus.RECEIPT,
      jdOrderStatus.INVALID_REPETITION_ORDER,
      jdOrderStatus.INVALID_CLOUD_STORE_ORDER,
      jdOrderStatus.INVALID_PLUS_FEE_ZERO,
      jdOrderStatus.INVALID_PAYMENT_GIFT,
      jdOrderStatus.PAY_DEPOSIT,
    ];
  }
}

export default jdOrderStatus
